<a href="https://colab.research.google.com/github/vanadnarayane26/Customer-Attrition-KDAG-Competition/blob/main/Customer_Attirition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!gdown https://drive.google.com/uc?id=1M_dGd1LUBVFf_YbRICQacFtNqVxlpYoe

Downloading...
From: https://drive.google.com/uc?id=1M_dGd1LUBVFf_YbRICQacFtNqVxlpYoe
To: /content/customerattritionprediction.zip
100% 280k/280k [00:00<00:00, 2.17MB/s]


In [ ]:
!unzip /content/customerattritionprediction.zip

Archive:  /content/customerattritionprediction.zip
replace Sample Submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: Sample Submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
!sudo apt-get install build-essential swig 
!curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install 
!pip install auto-sklearn==0.10.0

Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  swig swig3.0
0 upgraded, 2 newly installed, 0 to remove and 34 not upgraded.
Need to get 1,100 kB of archives.
After this operation, 5,822 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig3.0 amd64 3.0.12-1 [1,094 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig amd64 3.0.12-1 [6,460 B]
Fetched 1,100 kB in 1s (806 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontE

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import imblearn
import autosklearn.classification as classifier
print(sklearn.__version__)
print(imblearn.__version__)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


0.22.2.post1
0.4.3


/usr/local/lib/python3.7/dist-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)


In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.head()

ID     sex  ... GrandPayment CustomerAttrition
0  B60LHTZLLPFU4IULNPUF  Female  ...  4628.129119               Yes
1  1RUJ7ONYZHYTWKOKO1SD    Male  ...   922.085998                No
2  DZ9EEOQWSN0MYCBUPAM5    Male  ...  6205.891129               Yes
3  YZ43L1UQUQACTL1PXXZG    Male  ...  1248.655391                No
4  6P28152QGF60PDLSCB9M  Female  ...  1285.321277                No

[5 rows x 16 columns]

In [ ]:
df_test = pd.read_csv('test.csv')

In [ ]:
df_test_copy = df_test.copy()

In [ ]:
df_copy = df.copy()

In [ ]:
df['GrandPayment'].isnull().sum()

10

In [ ]:
df['GrandPayment'] = df['GrandPayment'].fillna(df['GrandPayment'].mean())

In [ ]:
df['GrandPayment'].isnull().sum()

0

In [ ]:
df_test['GrandPayment'] = df_test['GrandPayment'].fillna(df['GrandPayment'].mean())

In [ ]:
print(df_test.shape)

(705, 15)


In [ ]:
df_test.isnull().sum()

ID                     0
sex                    0
Aged                   0
Married                0
TotalDependents        0
ServiceSpan            0
MobileService          0
4GService              0
CyberProtection        0
HardwareSupport        0
TechnicalAssistance    0
FilmSubscription       0
SettlementProcess      0
QuarterlyPayment       0
GrandPayment           0
dtype: int64

In [ ]:
df = df.drop('ID',axis = 1)
df = pd.get_dummies(df)
df = df.drop(['sex_Female','Aged_No','Married_No','TotalDependents_No','MobileService_No','4GService_No','CyberProtection_No','HardwareSupport_No','TechnicalAssistance_No','FilmSubscription_No','SettlementProcess_Bank','CustomerAttrition_No'],axis = 1)

In [ ]:
df_test = df_test.drop('ID',axis = 1)
df_test = pd.get_dummies(df_test)
df_test = df_test.drop(['sex_Female','Aged_No','Married_No','TotalDependents_No','MobileService_No','4GService_No','CyberProtection_No','HardwareSupport_No','TechnicalAssistance_No','FilmSubscription_No','SettlementProcess_Bank'],axis = 1)

In [ ]:
y = df['CustomerAttrition_Yes'].values
X_test = df_test.values
print(X_test.shape)

(705, 17)


In [ ]:
df = df.drop('CustomerAttrition_Yes',axis = 1)
X = df.values

In [ ]:
from imblearn.over_sampling import SMOTE
smk = SMOTE(random_state=42)
X,y = smk.fit_sample(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
np.corrcoef(X)

array([[1.        , 0.99926576, 0.99999278, ..., 0.99884912, 0.99999974,
        0.9999904 ],
       [0.99926576, 1.        , 0.99923745, ..., 0.99881699, 0.99925575,
        0.99927443],
       [0.99999278, 0.99923745, 1.        , ..., 0.99866711, 0.99999305,
        0.9999992 ],
       ...,
       [0.99884912, 0.99881699, 0.99866711, ..., 1.        , 0.99884304,
        0.9986568 ],
       [0.99999974, 0.99925575, 0.99999305, ..., 0.99884304, 1.        ,
        0.99999035],
       [0.9999904 , 0.99927443, 0.9999992 , ..., 0.9986568 , 0.99999035,
        1.        ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X_test = sc_X.transform(X_test) 

In [ ]:
from sklearn.decomposition import  PCA
pca = PCA(n_components = 0.95)
X = pca.fit_transform(X)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.20163515 0.11881938 0.09643909 0.07306488 0.06583    0.06037597
 0.0589983  0.05708391 0.05567867 0.04319234 0.03970643 0.03642188
 0.02715297 0.0259899 ]


In [ ]:
np.corrcoef(X)

array([[ 1.        , -0.33081318,  0.1018931 , ...,  0.36688761,
         0.25981761, -0.54961823],
       [-0.33081318,  1.        , -0.00782675, ..., -0.32506637,
        -0.35487558, -0.30759031],
       [ 0.1018931 , -0.00782675,  1.        , ...,  0.02516154,
        -0.38522243, -0.4802785 ],
       ...,
       [ 0.36688761, -0.32506637,  0.02516154, ...,  1.        ,
        -0.33001689, -0.15337595],
       [ 0.25981761, -0.35487558, -0.38522243, ..., -0.33001689,
         1.        ,  0.33113816],
       [-0.54961823, -0.30759031, -0.4802785 , ..., -0.15337595,
         0.33113816,  1.        ]])

In [ ]:
print(X.shape)
print(y.shape)

(6338, 17)
(6338,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size = 0.15,random_state = 42)

In [ ]:
print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(5387, 17)
(951, 17)
(5387,)
(951,)


In [ ]:
#aUTOml
automlclassifier = classifier.AutoSklearnClassifier(time_left_for_this_task=3600, per_run_time_limit=50)
automlclassifier.fit(X_train,y_train)
y_pred = automlclassifier.predict(X_val)

In [ ]:
automlclassifier.show_models()

"[(0.820000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'gradient_boosting', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'one_hot_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'no_coalescense', 'data_preprocessing:numerical_transformer:imputation:strategy': 'most_frequent', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'robust_scaler', 'feature_preprocessor:__choice__': 'polynomial', 'classifier:gradient_boosting:early_stop': 'valid', 'classifier:gradient_boosting:l2_regularization': 1.4157943619253885e-10, 'classifier:gradient_boosting:learning_rate': 0.14242184931486887, 'classifier:gradient_boosting:loss': 'auto', 'classifier:gradient_boosting:max_bins': 255, 'classifier:gradient_boosting:max_depth': 'None', 'classifier:gradient_boosting:max_leaf_nodes': 15, 'classifier:gradient_boosting:min_samples_leaf': 38, 'classifier:gradient_boosting:scoring

In [ ]:
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
#only implement when want to use validation data
#tree = DecisionTreeClassifier()
#tree.fit(X_train,y_train)
#y_pred = tree.predict(X_val)
#y_pred_train = tree.predict(X_train)

# classifier = RandomForestClassifier(n_estimators = 72,criterion = 'entropy',random_state = 0,max_depth= 15, bootstrap = True,max_features = 'sqrt', min_samples_leaf = 1, min_samples_split =  5)
# # classifier.fit(X_train,y_train)
# # y_pred = classifier.predict(X_val)
# # y_pred_train = classifier.predict(X_train)
# classifier.fit(X,y)
# y_pred_new = classifier.predict(X)
# y_prediction_test = classifier.predict(X_test)

#SVM Classifier
# svclassifier = SVC(kernel='rbf')
# svclassifier.fit(X_train, y_train)
# y_pred = svclassifier.predict(X_val)
# y_pred_train = svclassifier.predict(X_train)

#xgboost
# xgb = XGBClassifier()
# xgb.fit(X_train,y_train)
# y_pred_train = xgb.predict(X_train)
# y_pred = xgb.predict(X_val)
# y_prediction_test = xgb.predict(X_test)

In [ ]:
#actual Training for submission
# xgb1 = XGBClassifier()
# xgb1.fit(X,y)
# y_prediction_test = xgb1.predict(X_test)
# classifier1 = RandomForestClassifier(n_estimators = 150,criterion = 'entropy',random_state = 0,max_depth = 7)
# classifier1.fit(X,y)
# y_prediction_test = classifier1.predict(X_test)

#SVM Classifier
# svclassifier1 = SVC(kernel='rbf')
# svclassifier1.fit(X, y)
# y_prediction_test = svclassifier1.predict(X_test)

In [ ]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 150, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [5,6,7,8,9,10,11,12,13,15,14]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
criterion = ['entropy','gini']
# Method of selecting samples for training each tree
bootstrap = [True, False]
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
               'criterion': criterion}
# print(param_grid)
#rf_Model = RandomForestClassifier()
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = RandomForestClassifier(), param_grid = param_grid, cv = 10, verbose=1, n_jobs = -1)
rf_Grid.fit(X, y)
print(rf_Grid.best_params_)
# #print(rf_Grid.acc)
print(rf_Grid.best_score_)

Fitting 10 folds for each of 3520 candidates, totalling 35200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   30.1s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  9.2min
[Parallel(n_jobs=-1)]: Done 796 tasks      | elapsed: 17.2min
[Parallel(n_jobs=-1)]: Done 1246 tasks      | elapsed: 27.8min
[Parallel(n_jobs=-1)]: Done 1796 tasks      | elapsed: 42.7min
[Parallel(n_jobs=-1)]: Done 2446 tasks      | elapsed: 60.4min
[Parallel(n_jobs=-1)]: Done 3196 tasks      | elapsed: 84.2min
[Parallel(n_jobs=-1)]: Done 4046 tasks      | elapsed: 112.2min
[Parallel(n_jobs=-1)]: Done 4996 tasks      | elapsed: 147.8min
[Parallel(n_jobs=-1)]: Done 6046 tasks      | elapsed: 188.0min
[Parallel(n_jobs=-1)]: Done 7196 tasks      | elapsed: 235.9min
[Parallel(n_jobs=-1)]: Done 8446 tasks      | elapsed: 289.4min
[Parallel(n_jobs=-1)]: Done 9796 tasks      | elapsed: 318.8min
[Parallel(n_jobs=-1)]: Done 11246 tasks 

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train,y_pred_train)
cm

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_val,y_pred)
cm

array([[607,  84],
       [132, 128]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       691
           1       0.60      0.49      0.54       260

    accuracy                           0.77       951
   macro avg       0.71      0.69      0.70       951
weighted avg       0.76      0.77      0.77       951



In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y,y_pred_new)
cm

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y,y_pred_new))

In [ ]:
df_sub = pd.DataFrame({'ID':df_test_copy['ID'],'CustomerAttrition':y_prediction_test})

In [ ]:
df_sub.shape

In [ ]:
df_sub

In [ ]:
df_sub = df_sub.replace({'CustomerAttrition':{0:'No',1:'Yes'}})

In [ ]:
df_sub

In [ ]:
df_sub.to_csv('sub_file.csv',index=False)